version: '2.1'

services:
  web:
    build:
      context: .
    ports:
      - 80:3000
    links:
      - db
    depends_on:
      - db
    stdin_open: true
  db:
    image: postgres
    volumes:
      - ./pgdata:/pgdata
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      PGDATA: /pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
