version: '2'

services:
  web:
    build:
      context: .
    ports:
      - 3000:80
    links:
      - db
    stdin_open: true
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
volumes:
  postgres-data:
    driver: local
